# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/reconcile-web',
                'doc_host': 'https://doyu.github.io',
                'git_url': 'https://github.com/doyu/reconcile-web',
                'lib_path': 'reconcile_web'},
  'syms': {'reconcile_web.archive': {}}}
