# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/reconcile-web',
                'doc_host': 'https://doyu.github.io',
                'git_url': 'https://github.com/doyu/reconcile-web',
                'lib_path': 'reconcile_web'},
  'syms': { 'reconcile_web.app': {'reconcile_web.app.create_app': ('app.html#create_app', 'reconcile_web/app.py')},
            'reconcile_web.archive': { 'reconcile_web.archive.list_months': ('archive.html#list_months', 'reconcile_web/archive.py'),
                                       'reconcile_web.archive.month_counts': ('archive.html#month_counts', 'reconcile_web/archive.py'),
                                       'reconcile_web.archive.safe_file': ('archive.html#safe_file', 'reconcile_web/archive.py'),
                                       'reconcile_web.archive.status_html': ('archive.html#status_html', 'reconcile_web/archive.py')}}}
