"""FastHTML viewer: auth gate + month index + month view + authed downloads

Docs: https://doyu.github.io/reconcile-web/app.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_app.ipynb.

# %% auto #0
__all__ = ['create_app', 'serve']

# %% ../nbs/01_app.ipynb #8b6a1971
import os, secrets
from pathlib import Path
from fasthtml.common import *
from starlette.responses import RedirectResponse, FileResponse, Response
from starlette.exceptions import HTTPException
from .archive import list_months, month_counts, status_html, safe_file, month_zip

# %% ../nbs/01_app.ipynb #26a2db0f
def create_app(
    archive_dir: str|Path|None = None,  # archive root (default: env ARCHIVE_DIR)
    password: str|None = None,          # shared password (default: env APP_PASSWORD)
    session_secret: str|None = None,    # session signing key (default: env SESSION_SECRET)
):
    "Build the FastHTML viewer app; raise RuntimeError on missing/invalid config"
    archive_dir = archive_dir or os.environ.get('ARCHIVE_DIR')
    app_password = password or os.environ.get('APP_PASSWORD')
    session_secret = session_secret or os.environ.get('SESSION_SECRET')
    missing = [n for n, v in (('ARCHIVE_DIR', archive_dir), ('APP_PASSWORD', app_password),
                              ('SESSION_SECRET', session_secret)) if not v]
    if missing: raise RuntimeError(f"missing config: {', '.join(missing)}")
    if not Path(archive_dir).is_dir(): raise RuntimeError(f"ARCHIVE_DIR is not a directory: {archive_dir}")

    def auth_before(req, session):
        if not session.get('auth'): return RedirectResponse('/login', status_code=303)

    def _check_month(month):
        if month not in list_months(archive_dir): raise HTTPException(404)

    # .nda/.html are the bank-issued raw statements, present only from 2026-07 on;
    # link what the month actually has so earlier months carry no dead links
    STATEMENTS = ('statement.nda', 'statement.html', 'statement.pdf', 'statement.csv')

    def statement_links(m):
        ls = [A(n, href=f'/m/{m}/{n}') for n in STATEMENTS if (Path(archive_dir)/m/n).is_file()]
        return P(*[x for a in ls for x in (' · ', a)][1:])

    # a page action, not a source file — bottom right of the month view, after
    # the table, never among the statement source links at the top
    def zip_link(m):
        return P(A('all.zip', href=f'/m/{m}/all.zip'), cls='zip-link')

    # app-wide CSS: missing-row highlight, inline expand buttons, tucked statement
    # links, and hiding status.md's own "# YYYY-MM — receipt status" H1 — the page
    # already names the month, and status.md is an opaque NotStr (never parsed)
    css = Style('.has-missing td {color: var(--pico-del-color, #c62828)}\n'
                'tbody button {width: auto; display: inline-block; padding: 0 .5em; margin-right: .5em}\n'
                'tr[id^="detail-"] p:first-child {margin: .25em 0}\n'
                'tr[id^="detail-"] h1, main > h1 ~ h1 {display: none}\n'
                '.zip-link {text-align: right}')

    # skip list covers only /login (every other route requires auth); the app serves no local
    # static files (Pico CSS comes from the CDN), so fast_app's default static route is removed
    # right after creation below — its extension list (pdf/csv) would otherwise shadow the
    # dotted file routes (.pdf/.csv) defined further down
    app, rt = fast_app(before=Beforeware(auth_before, skip=[r'/login']),
                       secret_key=session_secret, sess_https_only=True, hdrs=(css,))
    app.router.routes = [r for r in app.router.routes if getattr(r, 'path', None) != '/{fname:path}.{ext:static}']

    def login_page(error=False):
        body = [Form(Input(name='password', type='password', required=True),
                     Button('Login'), method='post', action='/login')]
        if error: body.insert(0, P('Wrong password'))
        return Titled('Login', *body)

    def expand_btn(m, oob=False):
        return Button('▸', hx_get=f'/m/{m}/expand', hx_target=f'#detail-{m}',
                      hx_swap='outerHTML', id=f'btn-{m}',
                      hx_swap_oob='true' if oob else None)

    def collapse_btn(m, oob=False):
        return Button('▾', hx_get=f'/m/{m}/collapse', hx_target=f'#detail-{m}',
                      hx_swap='outerHTML', id=f'btn-{m}',
                      hx_swap_oob='true' if oob else None)

    def month_row(m):
        c = month_counts(archive_dir, m)
        missing = c.get('missing', 0)
        return Tr(
            Td(expand_btn(m), A(m, href=f'/m/{m}')),
            Td(c.get('collected', 0)),
            Td(c.get('not-needed', 0)),
            Td(missing),
            cls='has-missing' if missing else None)

    def months_table():
        return Table(
            Thead(Tr(Th('month'), Th('collected'), Th('not-needed'), Th('missing'))),
            Tbody(*[el for m in reversed(list_months(archive_dir))
                    for el in (month_row(m), Tr(id=f'detail-{m}'))]))

    @rt('/login', methods=['GET'])
    def login_form(): return login_page()

    @rt('/login', methods=['POST'])
    def login_submit(password: str, session):
        if password and secrets.compare_digest(password.encode(), app_password.encode()):
            session['auth'] = True
            return RedirectResponse('/', status_code=303)
        return login_page(error=True)

    @rt('/logout', methods=['GET'])
    def logout(session):
        session.pop('auth', None)
        return RedirectResponse('/login', status_code=303)

    @rt('/', methods=['GET'])
    def index():
        return Titled('reconcile-archive',
                      months_table(),
                      P(A('Logout', href='/logout')))

    @rt('/m/{month}', methods=['GET'])
    def month_view(month: str):
        _check_month(month)
        return Titled(month,
            statement_links(month),
            NotStr(status_html(archive_dir, month)),
            zip_link(month),
            P(A('← months', href='/')))

    def _file(month, kind, name=None, media_type=None):
        try: return FileResponse(safe_file(archive_dir, month, kind, name), media_type=media_type)
        except FileNotFoundError: raise HTTPException(404)

    @rt('/m/{month}/statement.pdf', methods=['GET'])
    def statement_pdf(month: str): return _file(month, 'statement_pdf')

    @rt('/m/{month}/statement.csv', methods=['GET'])
    def statement_csv(month: str): return _file(month, 'statement_csv')

    @rt('/m/{month}/statement.nda', methods=['GET'])
    def statement_nda(month: str): return _file(month, 'statement_nda')

    # the bank issues this HTML as ISO-8859-1; the Content-Type header overrides the
    # file's own <meta charset>, so declare it or Finnish ä/ö arrive as mojibake
    @rt('/m/{month}/statement.html', methods=['GET'])
    def statement_html_file(month: str):
        return _file(month, 'statement_html', media_type='text/html; charset=ISO-8859-1')

    @rt('/m/{month}/receipt/{name}', methods=['GET'])
    def receipt(month: str, name: str): return _file(month, 'receipt', name)

    # built on the fly, in memory — the zip always mirrors the month dir as pushed
    @rt('/m/{month}/all.zip', methods=['GET'])
    def month_zip_file(month: str):
        try: body = month_zip(archive_dir, month)
        except FileNotFoundError: raise HTTPException(404)
        return Response(body, media_type='application/zip',
                        headers={'Content-Disposition': f'attachment; filename="ninjalabo-{month}.zip"'})

    @rt('/m/{month}/expand', methods=['GET'])
    def expand(month: str):
        _check_month(month)
        return (Tr(Td(statement_links(month), NotStr(status_html(archive_dir, month)), zip_link(month), colspan=4), id=f'detail-{month}'), collapse_btn(month, oob=True))

    @rt('/m/{month}/collapse', methods=['GET'])
    def collapse(month: str):
        _check_month(month)
        return Tr(id=f'detail-{month}'), expand_btn(month, oob=True)

    return app

# %% ../nbs/01_app.ipynb #faed463d
def serve(
    host: str = '0.0.0.0',  # bind address
    port: int = 8000,       # port
):
    "Run the viewer under uvicorn; config comes from env"
    import uvicorn
    uvicorn.run(create_app(), host=host, port=port)
