"""FastHTML viewer: auth gate + month index + month view + authed downloads

Docs: https://doyu.github.io/reconcile-webapp.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_app.ipynb.

# %% auto #0
__all__ = ['create_app']

# %% ../nbs/01_app.ipynb #8b6a1971
import os, secrets
from pathlib import Path
from fasthtml.common import fast_app, Beforeware, Titled, Form, Input, Button, P, Ul, Li, A, NotStr
from starlette.responses import RedirectResponse, FileResponse
from starlette.exceptions import HTTPException
from .archive import list_months, month_counts, status_html, safe_file

# %% ../nbs/01_app.ipynb #26a2db0f
def create_app(
    archive_dir: str|Path|None = None,  # archive root (default: env ARCHIVE_DIR)
    password: str|None = None,          # shared password (default: env APP_PASSWORD)
    session_secret: str|None = None,    # session signing key (default: env SESSION_SECRET)
):
    "Build the FastHTML viewer app; raise RuntimeError on missing/invalid config"
    archive_dir = archive_dir or os.environ.get('ARCHIVE_DIR')
    app_password = password or os.environ.get('APP_PASSWORD')
    session_secret = session_secret or os.environ.get('SESSION_SECRET')
    missing = [n for n, v in (('ARCHIVE_DIR', archive_dir), ('APP_PASSWORD', app_password),
                              ('SESSION_SECRET', session_secret)) if not v]
    if missing: raise RuntimeError(f"missing config: {', '.join(missing)}")
    if not Path(archive_dir).is_dir(): raise RuntimeError(f"ARCHIVE_DIR is not a directory: {archive_dir}")

    def auth_before(req, session):
        if not session.get('auth'): return RedirectResponse('/login', status_code=303)

    # skip only /login: the app serves no local static files (Pico CSS comes from the CDN), and
    # FastHTML's default static route can serve pdf/csv from cwd — an exempted path would bypass auth
    app, rt = fast_app(before=Beforeware(auth_before, skip=[r'/login']),
                       secret_key=session_secret, sess_https_only=True)

    def login_page(error=False):
        body = [Form(Input(name='password', type='password', required=True),
                     Button('Login'), method='post', action='/login')]
        if error: body.insert(0, P('Wrong password'))
        return Titled('Login', *body)

    @rt('/login', methods=['GET'])
    def login_form(): return login_page()

    @rt('/login', methods=['POST'])
    def login_submit(password: str, session):
        if password and secrets.compare_digest(password, app_password):
            session['auth'] = True
            return RedirectResponse('/', status_code=303)
        return login_page(error=True)

    @rt('/logout', methods=['GET'])
    def logout(session):
        session.pop('auth', None)
        return RedirectResponse('/login', status_code=303)

    @rt('/', methods=['GET'])
    def index():
        items = [Li(A(m, href=f'/m/{m}'),
                    f" — collected {c.get('collected', 0)}, not-needed {c.get('not-needed', 0)},"
                    f" missing {c.get('missing', 0)}")
                 for m in list_months(archive_dir) for c in [month_counts(archive_dir, m)]]
        return Titled('reconcile-archive', Ul(*items), P(A('Logout', href='/logout')))

    @rt('/m/{month}', methods=['GET'])
    def month_view(month: str):
        if month not in list_months(archive_dir): raise HTTPException(404)
        return Titled(month,
            P(A('statement.pdf', href=f'/m/{month}/statement.pdf'), ' · ',
              A('statement.csv', href=f'/m/{month}/statement.csv')),
            NotStr(status_html(archive_dir, month)),
            P(A('← months', href='/')))

    return app
