"""Read-only access to the reconcile-archive checkout

Docs: https://doyu.github.io/reconcile-webarchive.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_archive.ipynb.

# %% auto #0
__all__ = ['MONTH_RE', 'list_months']

# %% ../nbs/00_archive.ipynb #3c774379
import re, html
from pathlib import Path
import markdown as md

# %% ../nbs/00_archive.ipynb #790aebe3
MONTH_RE = re.compile(r'^\d{4}-\d{2}$')

def list_months(
    archive_dir: str|Path,  # path to the reconcile-archive checkout
) -> list[str]:             # sorted month names like '2025-07'
    "Month directories (YYYY-MM containing a status.md) in sorted order"
    return sorted(p.name for p in Path(archive_dir).iterdir()
                  if p.is_dir() and MONTH_RE.match(p.name) and (p/'status.md').exists())
