"""Read-only access to the reconcile-archive checkout

Docs: https://doyu.github.io/reconcile-webarchive.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_archive.ipynb.

# %% auto #0
__all__ = ['MONTH_RE', 'MISSING_RE', 'RECEIPT_LINK_RE', 'HREF_RE', 'list_months', 'month_counts', 'status_html', 'safe_file']

# %% ../nbs/00_archive.ipynb #3c774379
import re, html
from pathlib import Path
import markdown as md

# %% ../nbs/00_archive.ipynb #790aebe3
MONTH_RE = re.compile(r'^\d{4}-\d{2}$')

def list_months(
    archive_dir: str|Path,  # path to the reconcile-archive checkout
) -> list[str]:             # sorted month names like '2025-07'
    "Month directories (YYYY-MM containing a status.md) in sorted order"
    return sorted(p.name for p in Path(archive_dir).iterdir()
                  if p.is_dir() and MONTH_RE.match(p.name) and (p/'status.md').exists())

# %% ../nbs/00_archive.ipynb #781ece76
MISSING_RE = re.compile(r'\*\*missing[^:]*:\s*(\d+)\*\*')

def month_counts(
    archive_dir: str|Path,  # archive root
    month: str,             # month name like '2025-07'
) -> dict:                  # raw status tokens -> count, plus 'missing' from the footer line
    "Tally the status column of status.md; read missing from the footer"
    text = (Path(archive_dir)/month/'status.md').read_text()
    counts = {}
    for line in text.splitlines():
        line = line.strip()
        if not line.startswith('|'): continue
        cells = [c.strip() for c in line.strip('|').split('|')]
        if len(cells) < 4: continue
        tok = cells[3]
        if not tok or tok.lower() == 'status' or set(tok) <= {'-'}: continue  # header/separator rows
        counts[tok] = counts.get(tok, 0) + 1
    m = MISSING_RE.search(text)
    if m is None: raise ValueError(f"{month}/status.md: missing-count footer line not found")
    counts['missing'] = int(m.group(1))
    return counts

# %% ../nbs/00_archive.ipynb #cc74fdc9
RECEIPT_LINK_RE = re.compile(r'\]\(receipts/([A-Za-z0-9._-]+\.pdf)\)')
HREF_RE = re.compile(r'href="(?!/m/)[^"]*"')  # any rendered href not pointing at an authed route

def status_html(
    archive_dir: str|Path,  # archive root
    month: str,             # month name like '2025-07'
) -> str:                   # HTML fragment of the rendered status.md
    "Render status.md to HTML: rewrite receipt links, escape raw HTML, allowlist hrefs"
    text = (Path(archive_dir)/month/'status.md').read_text()
    text = RECEIPT_LINK_RE.sub(rf'](/m/{month}/receipt/\1)', text)
    out = md.markdown(html.escape(text, quote=False), extensions=['tables'])
    return HREF_RE.sub('', out)  # Markdown [x](javascript:…) survives escaping; only /m/… hrefs pass

# %% ../nbs/00_archive.ipynb #14f0125a
def safe_file(
    archive_dir: str|Path,  # archive root
    month: str,             # month name like '2025-07'
    kind: str,              # 'statement_pdf' | 'statement_csv' | 'receipt'
    name: str|None = None,  # receipt filename (receipt kind only)
) -> Path:                  # resolved file inside the month dir
    "Resolve a servable file; raise FileNotFoundError on traversal or anything missing"
    if not MONTH_RE.match(month): raise FileNotFoundError(month)
    root = Path(archive_dir).resolve()
    mdir = (root/month).resolve()
    if not mdir.is_relative_to(root): raise FileNotFoundError(month)  # month dir symlinked out
    if kind == 'statement_pdf':   p = mdir/'statement.pdf'
    elif kind == 'statement_csv': p = mdir/'statement.csv'
    elif kind == 'receipt':
        if not name or name != Path(name).name or not name.endswith('.pdf'):
            raise FileNotFoundError(name)
        p = mdir/'receipts'/name
    else: raise FileNotFoundError(kind)
    try:
        rp = p.resolve()  # follows symlinks; an escaping symlink lands outside mdir
        ok = rp.is_file() and rp.is_relative_to(mdir)
    except (ValueError, RuntimeError, OSError):  # null bytes, symlink loops, ...
        raise FileNotFoundError(p) from None
    if not ok: raise FileNotFoundError(p)
    return rp
