"""Read-only access to the reconcile-archive checkout

Docs: https://doyu.github.io/reconcile-webarchive.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_archive.ipynb.

# %% auto #0
__all__ = ['MONTH_RE', 'MISSING_RE', 'list_months', 'month_counts']

# %% ../nbs/00_archive.ipynb #3c774379
import re, html
from pathlib import Path
import markdown as md

# %% ../nbs/00_archive.ipynb #790aebe3
MONTH_RE = re.compile(r'^\d{4}-\d{2}$')

def list_months(
    archive_dir: str|Path,  # path to the reconcile-archive checkout
) -> list[str]:             # sorted month names like '2025-07'
    "Month directories (YYYY-MM containing a status.md) in sorted order"
    return sorted(p.name for p in Path(archive_dir).iterdir()
                  if p.is_dir() and MONTH_RE.match(p.name) and (p/'status.md').exists())

# %% ../nbs/00_archive.ipynb #781ece76
MISSING_RE = re.compile(r'\*\*missing[^:]*:\s*(\d+)\*\*')

def month_counts(
    archive_dir: str|Path,  # archive root
    month: str,             # month name like '2025-07'
) -> dict:                  # raw status tokens -> count, plus 'missing' from the footer line
    "Tally the status column of status.md; read missing from the footer"
    text = (Path(archive_dir)/month/'status.md').read_text()
    counts = {}
    for line in text.splitlines():
        line = line.strip()
        if not line.startswith('|'): continue
        cells = [c.strip() for c in line.strip('|').split('|')]
        if len(cells) < 4: continue
        tok = cells[3]
        if not tok or tok.lower() == 'status' or set(tok) <= {'-'}: continue  # header/separator rows
        counts[tok] = counts.get(tok, 0) + 1
    m = MISSING_RE.search(text)
    if m is None: raise ValueError(f"{month}/status.md: missing-count footer line not found")
    counts['missing'] = int(m.group(1))
    return counts
