"""Fill in a module description here

Docs: https://doyu.github.io/reconcile-webcore.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['foo']

# %% ../nbs/00_core.ipynb #72a1e50f
def foo(): pass
