"""Update the running box to the pushed main: `reconcile-deploy`

Docs: https://doyu.github.io/reconcile-web/deploy.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_deploy.ipynb.

# %% auto #0
__all__ = ['deploy_cmd', 'reconcile_deploy']

# %% ../nbs/03_deploy.ipynb #de060606
def deploy_cmd(
    host:str="doyu@box.ninjalabo.ai",  # ssh target (sudo-capable login user)
    deps:bool=False,                   # also reinstall dependencies
)->list:                               # ssh argv
    "Build the ssh argv: pip reinstall from GitHub main + recipe perms + restart."
    nd = "" if deps else " --no-deps"
    remote = (
        "set -e\n"
        f"sudo /opt/reconcile/bin/pip install --upgrade --force-reinstall{nd} git+https://github.com/doyu/reconcile-web.git\n"
        # the recipe's permission lines, verbatim: root's pip writes under its
        # umask, and the service user reads the venv via group only
        "sudo chown -R root:reconcile /opt/reconcile\n"
        "sudo chmod -R u=rwX,g=rX,o= /opt/reconcile\n"
        "sudo systemctl restart reconcile\n"
        "systemctl is-active reconcile\n")
    return ["ssh", host, remote]

# %% ../nbs/03_deploy.ipynb #de090909
import subprocess, sys
from pathlib import Path
from fastcore.script import call_parse

@call_parse
def reconcile_deploy(
    host:str="doyu@box.ninjalabo.ai",  # ssh target (sudo-capable login user)
    repo:str="~/reconcile-web",        # local checkout, used to check HEAD is pushed
    deps:bool=False,                   # also reinstall dependencies
):
    "Deploy the pushed main to the box: pip reinstall + recipe perms + restart"
    d = Path(repo).expanduser()
    if (d/".git").exists():
        run = lambda *a: subprocess.run(a, capture_output=True, text=True).stdout.split()
        local, remote = run("git", "-C", str(d), "rev-parse", "HEAD"), run("git", "-C", str(d), "ls-remote", "origin", "main")
        if local and remote and local[0] != remote[0]:
            sys.exit(f"local HEAD {local[0][:7]} != origin/main {remote[0][:7]} — push first (the box installs from GitHub main)")
    cmd = deploy_cmd(host, deps)
    print(f"deploying origin/main to {host}", file=sys.stderr)
    raise SystemExit(subprocess.run(cmd).returncode)
