"""Push the local archive checkout to the box: `reconcile-push`, the monthly one-liner

Docs: https://doyu.github.io/reconcile-websync.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_sync.ipynb.

# %% auto #0
__all__ = ['push_cmd', 'reconcile_push']

# %% ../nbs/02_sync.ipynb #ff66aa77
from pathlib import Path

def push_cmd(
    src:str="~/reconcile-archive",  # archive checkout (source of truth)
    dest:str="doyu@box.ninjalabo.ai:/srv/reconcile-archive",  # rsync target on the box
    dry_run:bool=False,             # add rsync --dry-run
)->list:                            # rsync argv
    "Build the rsync argv: archive push with the box's group-read/setgid policy baked in."
    src = str(Path(src).expanduser())
    # --no-group: -a would preserve the laptop's group (doyu), locking out the
    # box's reconcile service user; the destination's setgid dir sets the group
    return ["rsync", "-a", "--no-group", "--delete", "--chmod=D2750,F640",
            *(["--dry-run"] if dry_run else []),
            f"{src.rstrip('/')}/", f"{dest.rstrip('/')}/"]

# %% ../nbs/02_sync.ipynb #cc99dd00
import subprocess, sys
from fastcore.script import call_parse

@call_parse
def reconcile_push(
    src:str="~/reconcile-archive",  # archive checkout (source of truth)
    dest:str="doyu@box.ninjalabo.ai:/srv/reconcile-archive",  # rsync target on the box
    dry_run:bool=False,             # preview: rsync --dry-run
):
    "Push the archive to the box (the viewer reads it live; no restart needed)"
    cmd = push_cmd(src, dest, dry_run)
    print(" ".join(cmd), file=sys.stderr)
    raise SystemExit(subprocess.run(cmd).returncode)
